### ISSUE TITLE
sonar

### ISSUE THREAD

**Issue by grigoriy-romanenko** [KorzhArtem1996/testTask#14]
проверить проект через sonarqube и исправить ошибки
https://docs.sonarqube.org/latest/setup/get-started-2-minutes/

**Comment by grigoriy-romanenko** [comment]
попробуй поднять покрытие кода тестами до 100%, мин. 80%

**Comment by grigoriy-romanenko** [comment]
исправь ошибки в тестах
для тестов нужна отдельная бд
`[ERROR] Tests run: 7, Failures: 3, Errors: 1, Skipped: 0, Time elapsed: 0.341 s <<< FAILURE! - in ua.korzh.testproject.service.client.ClientServiceImplTest
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ua.korzh.testproject.model.Client.accounts, could not initialize proxy - no Session
	at ua.korzh.testproject.service.client.ClientServiceImplTest.getAll(ClientServiceImplTest.java:39)
[ERROR] register  Time elapsed: 0.073 s  <<< FAILURE!
java.lang.AssertionError: expected:<Client{id=3, email='artem', password='1234', accounts=[Account{id = 3, balance = 0, clients id =3}]}> but was:<Client{id=2, email='withdraw', password='lllll', accounts=[Account{id = 2, balance = 100, clients id =2}]}>
	at ua.korzh.testproject.service.client.ClientServiceImplTest.register(ClientServiceImplTest.java:62)
[ERROR] getById  Time elapsed: 0.05 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Client{id=[4, email='getById', password='12345', accounts=[Account{id = 4, balance = 0, clients id =4]}]}> but was:<Client{id=[5, email='getById', password='12345', accounts=[Account{id = 5, balance = 0, clients id =5]}]}>
	at ua.korzh.testproject.service.client.ClientServiceImplTest.getById(ClientServiceImplTest.java:48)
[ERROR] deposit  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Account{id = [6, balance = 0, clients id =6]}> but was:<Account{id = [7, balance = 0, clients id =7]}>
	at ua.korzh.testproject.service.client.ClientServiceImplTest.deposit(ClientServiceImplTest.java:70)`

**Comment by grigoriy-romanenko** [comment]
перед выполнением тестов нужно очищать тестовую бд

**Comment by grigoriy-romanenko** [comment]
AccountRestControllerTest
заменить import org.junit.jupiter.api.Test;
на import org.junit.Test;

**Comment by grigoriy-romanenko** [comment]
depositMoneyTest()
зачем 2 раза выполнять запрос
вместо anyLong(), anyInt() нужно использовать eq()
в put("/clients/1/accounts/1/deposit?money=500") нужно использовать параметр uriVars для передачи clientId и accountId

**Comment by grigoriy-romanenko** [comment]
depositMoneyTest()
удали переменную `client`, она не используется
добавь переменные `long money = 500L`, `int clientId = 1`, `int accountId = 1` и используй их в `clientService.deposit(...)`, `put("/clients/{clientId}/accounts/{accountId}/deposit?money={money}", ...)`
удали `account2` из `willReturn(account1, account2)`
удали `accept(MediaType.APPLICATION_JSON)`, добавь проверку content type header в ответе

**Comment by grigoriy-romanenko** [comment]
checkBalanceTest()
удали переменную `client`, она не используется

**Comment by grigoriy-romanenko** [comment]
showTransactionTest()
добавь проверку body ответа

**Comment by grigoriy-romanenko** [comment]
AccountRestControllerExceptionHandlerTest
вместо `"<400 BAD_REQUEST Bad Request,Account not exist,[]>"` нужно проверять поля ResponseEntity

**Comment by grigoriy-romanenko** [comment]
registerClientTest()
используй параметр uriVars в запросах

**Comment by grigoriy-romanenko** [comment]
ClientServiceImplTest
повторяющиеся значения нужно выносить в переменную, `String email = "artem"`, `long money = 500L`
перенеси `assertThrows` в блок проверок
в `deposit()` и `withdraw() ` нужно проверять assertEquals(initialBalance + money, actualBalance)
в `showTransaction()` добавь проверку количества транзакций

**Comment by grigoriy-romanenko** [comment]
void createTransaction(OperationName operationName, Account account, long money)
всегда возвращает OperationName.DEPOSIT
добавить тесты

**Comment by grigoriy-romanenko** [comment]
AccountService
удали `void addMoney(Account account, long balance)` и `void withDrawMoney(Account account, long sum)`

ClientService
удали методы 
```
Account deposit(long money, int accountId);
Account withdraw(long sum, int accountId);
long checkBalance(int accountId);
List<Transaction> showTransaction(int accountId);
```

**Comment by grigoriy-romanenko** [comment]
добавь properties для тестового окружения
в тестах нужно использовать отдельную схему бд
